package com.nfldraftscience.domain;

public enum Route {
    HITCH, SLANT, CURL, ARROW, DIG, OUT, QUICK_OUT, POST, CORNER, POST_CORNER, 
    SAIL, GO, FADE, COME_BACK,SQUARE_IN, DIAG, FLAT, HINGE, OVER, UNDER, HIDE, SLUGGO,
    HIDE_OUT, BENCH, STOP, CROSS, DELAY, SEAM
}
